### ISSUE TITLE
arsenal tableby control "fe" test issue

### ISSUE THREAD

**Issue by mhadeshwar** [mayoverse/arsenal#341]
So when i use the "fe" test in tableby control, and when I run the the summary it always end up with the following result

Show in New Window
 Error in stats::fisher.test(tab, simulate.p.value = simulate.p.value, : 
FEXACT error 7(location). LDSTP=18600 is too small for this problem,
(pastp=32.3805, ipn_0:=ipoin[itp=122]=150, stp[ipn_0]=33.3709).
Increase workspace or consider using 'simulate.p.value=TRUE'

**Comment by sinnweja** [comment]
The combinatorics for high counts in the 2x2 table of a Fisher's test get computationally intensive.  In other words, Fisher's exact test works best with small cell counts. Can you hard-code the setting of simulate.p.value to TRUE for your run of tableby?

**Comment by mhadeshwar** [comment]
hi


my cross tab is actually 4×3 or more more rows .
can you please tell me how to resolve this?

**Comment by sinnweja** [comment]
I would suggest using the chi-square test ("chisq" instead of "fe") in that case. Fisher's would be okay in 4x3 tables with small cell counts and ordinal categories, but the error is indicating R is struggling with the calculations. There is a simulate.p.value option for the chi-square test as well, but it is more likely to work than fisher's without the simulated p-values. Note the option for continuity correction ("chisq.correct") as well.

**Comment by mhadeshwar** [comment]
thanks for the suggestion.
